### ISSUE TITLE
Multi mapping query

### ISSUE THREAD

**Issue by blobor** [StackExchange/dapper-dot-net#156]
Could you please increase count of input parameters up to 16, like it implemented by Microsoft BCL (for example  Action<T1,  ,T16> delegate)

**Comment by NickCraver** [comment]
@blobor I think it's unlikely that we'll add more return types simply because it doesn't scale. There's an inherent problem with support and bulk with rapidly diminishing returns (see my comments on a related PR #245). There's an arbitrary type limit method via:

```
public static IEnumerable<TReturn> Query<TReturn>(
  this IDbConnection cnn, 
  string sql, 
  Type[] types, Func<object[], TReturn> map, 
  dynamic param = null, 
  IDbTransaction transaction = null,
  bool buffered = true, 
  string splitOn = "Id", 
  int? commandTimeout = null, 
  CommandType? commandType = null
)
```

As for the type safety, if that's a deciding factor then I'd suggest another package that adds MultiMap overloads with large numbers of parameters (this may already exist). It's not ideal *for the core package* for the reasons I enumerated in that PR, but if someone wants to maintain the huge counts elsewhere that's no in the main line of pull requests and such then they are certainly welcome to do so. It just needs to live outside the main stack, that's the primary concern here.

Admittedly, when we break SqlMapper.cs out into more files (merges are a pain at it's current size), this becomes less of a concern, but the other negatives will remain after that split.
