### ISSUE TITLE
Multi map with <T, dynamic>

### ISSUE THREAD

**Issue by programcsharp** [StackExchange/dapper-dot-net#215]
Is this possible? It'd be very useful in cases with some static columns and some dynamic columns, for example a PIVOT.

**Comment by NickCraver** [comment]
It's not currently possible - can you layout your use case? I can't think of a scenario where there's not an alternative approach that likely ends up being a bit cleaner. I'm happy to help if you can pitch out an example here.

**Comment by johncrim** [comment]
I agree that this would be useful.  Eg a query like:

 `select userid, username, attr1, attr2, .... attr40 from users u join demographics d on u.userid = d.userid where u.orgid=1234`

I'd want this to return 2 objects for multimapping - a `User` object, and a dynamic (or dictionary-like) object so I can lookup the demographic attributes by name.  Eg `attributes[key]` instead of `attributes.attr1`.

**Comment by NickCraver** [comment]
@johncrim wouldn't something like `this[string property]` accessor support be more appropriate there? What's the return type in your scenario if not `User`? A more complete example would help!

**Comment by johncrim** [comment]
I found this issue before testing it out (I searched b/c I didn't see any documentation for this use case) - it turns out that the support I need for this is already in place.

Here's what I ended up using:
```
var command = new CommandDefinition("select * from Users u join UserDemographics d on u.UserId = d.UserId", cancellationToken: cancellationToken);
var users = await cn.QueryAsync<User, dynamic, User>(command, 
                                                                                          (user, dynamicDemos) =>
                                                                                          {
                                                                                          var demos = new DemoWrapper((IDictionary<string, object>) dynamicDemos);
                                                                                          user.Demographics = demos;
                                                                                          return user;
                                                                                          },
                                                                                          splitOn: "attr1");
```

Where UserDemographics is a pivoted table with a lot of columns.  This approach allowed me to access the values from that table as a dictionary.

Thank you for the help!
