### ISSUE TITLE
Passing arrays/datatables as xml

### ISSUE THREAD

**Issue by dimzon** [StackExchange/dapper-dot-net#233]
I discovered most enterprise-level RDBMS (Oracle/DB2/MSSQL/Postrgess) supports XML to TABLE 

http://docs.oracle.com/cd/B19306_01/server.102/b14200/functions228.htm
http://stackoverflow.com/questions/3989395/convert-xml-to-table-sql-server

I'm using this to pass arrays(including non-primitive arrays ie datatables) into both DB2/MSSQL in production. Works like a charm :)

**Comment by NickCraver** [comment]
I'm not sure what's being asked for here, can you please clarify?

**Comment by NickCraver** [comment]
Closing this out due to idleness - if someone can clarify please respond and I'll re-open. As it stands I'm finding it hard to see what this would look like or imagine its usage. While SQL Server "can do it", it's not really "supported" - it'd be a very manual process which you could do with parameters today. I'm not sure what such an API would look like on the other providers, given the varying APIs on the server-side for it which also differs a bit by version.
