### ISSUE TITLE
What Is a DeadValue?

### ISSUE THREAD

**Issue by AndrewKL** [StackExchange/dapper-dot-net#238]
recently I've found a situation in which the if a <dynamic> is queried dapper occasionally returns a row with null values and some DeadValue class.  What exactly is DeadValue used to represent?

**Comment by AndrewKL** [comment]
So I don't know if this fully classifies as a bug but it turns out that if you multiply enumerate a query of dynamic that the second enumeration returns a list with none of its properties set and or set to DeadValue.

**Comment by mgravell** [comment]
DeadValue is used to represent something that *shouldn't be there*. Imagine
the data for a dynamic row was based on Dictionary`2 - you could just
Remove(key). You can't do this for dapper rows because the columns are (for
memory etc) common between all rows from the same query. The idea is that
we pretend it isn't there and lie and cheat and steal.

If you're seeing it: that's a bug. Do you have a full repro example?

**Comment by NickCraver** [comment]
@AndrewKL any update on this? With a repro we're a bit lost on any potential causes here.
