### ISSUE TITLE
Null Reference Exception - parameters.Get<string>("name")

### ISSUE THREAD

**Issue by daveed80** [StackExchange/dapper-dot-net#247]
I would expect the below to return the corresponding value for the given key. However, it returns

'Null Reference Exception - Object reference not set to an instance of an object.'

Any thoughts on this??????

DynamicParameters parameters = new DynamicParameters();

parameters.Add("@parameter", "test");

string test = parameters.Get<string>("parameter");

**Comment by daveed80** [comment]
I've also tried

string test = parameters.Get("@parameter")

but still encounter the exception....

**Comment by tomexou** [comment]
You need to declare the parameter as Direction.InputOuput  and execute the SQL, then you will get the value. The method wrapping and naming is not well and easy to misunderstand.

**Comment by NickCraver** [comment]
Closing this out, as @tomexou does a good job of explaining correct usage of parameters. The exception is there to prevent reading out what people *assume* is set in some cases. Since you have the value you would *set*, it protects from all the cases of reading too early and getting not-yet-set values - which seems to be what was hit here.
