### ISSUE TITLE
Sqlbuilder template regex

### ISSUE THREAD

**Issue by madagaga** [StackExchange/dapper-dot-net#280]
The current regular expression in Sqlbuilder template causes issue when clause is at the begining.
For example `"SELECT /** whatever **/ F1, F2 .. From T1  /** where **/"`
the result is `"SELECT "` 

Replacing with this regex will fix the issue: `\/ \*\*[^\*]*\*\*\/`

**Comment by jods4** [comment]
After replacing placeholders, Dapper removes unused templates with the regex on L67, which is `/\*\*.+\*\*\/`.
The issue here is that Regex is greedy by default, so `.+` will match as much as possible (i.e. the whole string) and backtrack from there until it matches the end of the pattern (`**/`). This is inefficient (backtracking a long string) and matches far too much if your template looks like `/** 1 **/ keep this /** 2 **/`.

The proposed solution is ok-ish in this case but not perfect. By not matching `*`, the following block will not match: `/** x*y **/`.

I suggest using a non-greedy modifier `.+?`, the full regex becomes `/\*\*.+?\*\*\/`.
A non-greedy regex will match as little as possible, which is exactly what we want. 
It will perform better and match the comments correctly, even when there's a star inside.

Another option comes to mind: obviously the syntax `/** xyz **/` was chosen because it is a SQL comment, hence valid SQL. So why remove the unused templates _at all_? I guess it would be even more efficient to do nothing, no?

**Comment by jods4** [comment]
PR #625 fixes this bug, assuming you want to keep removing the unused comments/templates.
@NickCraver would be nice if you could merge and publish an updated package. This has been open for 1.5 years and can generate at best incorrect SQL, at worse security issues.

**Comment by mgravell** [comment]
Merged PR
