### ISSUE TITLE
About change notes for last releases

### ISSUE THREAD

**Issue by rafakwolf** [StackExchange/dapper-dot-net#283]
Sorry by asking this here but, exists any change notes for .41 and .42 versions.
Thanks

**Comment by mgravell** [comment]
Good question; I forget to update the release notes because I've been transitioning between nuspec and project.json, and the latter doesn't support release notes yet.

The change was simply: when using literal injection with booleans, 1/0 should be used instead of true/false. This was applied correctly in one place but not another; now it is applied correctly in both.

**Comment by rafakwolf** [comment]
OK, thanks for your attention.
