### ISSUE TITLE
Document EF type handlers

### ISSUE THREAD

**Issue by togakangaroo** [StackExchange/dapper-dot-net#322]
It seems like there's some stuff in here around allowing Dapper to read EF type maps but I can't find a shred of documentation to that effect...

**Comment by NickCraver** [comment]
I'm not sure that anything you're talking about exists, Dapper only plugs in type handlers for Entity Framework - there's no special support beyond that.

It's not that it's unwelcomed, we just don't use EF and so spend very little time on it. I'm not sure what enhancements even make sense for EF, I lack the expertise in the daily trouble areas since we avoid it on the performance front. I'm going to close this out since *that* feature doesn't exist - feel free to pitch features you'd like to see and (hopefully) fit Dapper's goals though!
