### ISSUE TITLE
SqlMapper.GetColumnHash does not take column type into consideration

### ISSUE THREAD

**Issue by jslew** [StackExchange/dapper-dot-net#329]
There is a comment in `SqlMapper.GetColumnHash()` that indicates that this is intentional:
```
// binding code is only interested in names - not types
```
This can cause exceptions if (for example) a sproc's resultset's output changes from (for example) `sbyte/TINYINT` to `UInt64/TINYINT`.  Say that column is being mapped to a DTO bool, so the underlying size difference is irrelevant to the ultimate result -- but since the cache does not consider this to be a relevant difference, the compiled `DeserialiserState.Func` will crash with an `InvalidCastException`.  The comment does not say *why* binding code is only interested in names, so wondering if a PR that expanded the definition of `GetColumnHash` to include column types would be accepted, or if there is some further reasoning about this that makes it necessary to remain as-is.

**Comment by NickCraver** [comment]
I think the change to include column type makes sense here technically, but it does add a cost on every read which was likely the original reason for leaving it out. Unfortunately though, we can only reliably get the .Net type here, not the database type due to CoreCLR lacking information there (and that route is *really* expensive by comparison anyway). 

I think we should instead make sure we determine this mis-match case and flush the cache accordingly on-error, resulting in an erring but self-fixing use case. I think that's the more sane route given the 99.9999999% wasteful effort added here by doing such a check every time.

**Comment by mgravell** [comment]
For context: I actually want to split the existing code quite a but here at
the moment the result is subordinate to the command, which prevents reuse
and makes it hard to expose a requested "I ave a reader, you parse the data
for me" API.

My plan was to address both things at the same time, making readers
first-level citizens.

**Comment by mgravell** [comment]
Fixed https://github.com/StackExchange/dapper-dot-net/commit/c80e9d17488425006de1b6e33dc3989ab7251e84
