### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by DarekDan** [StackExchange/dapper-dot-net#333]
I am just curious ... How come there are no Unit Tests in this solution, and instead there are only Program(s) testing the functionality? What is the benefit here?

**Comment by DarekDan** [comment]
I forked into a new repository, https://github.com/DarekDan/dapper-dot-net, and if the community approves, I will create a pull request after all tests have been migrated. Using a unit test class helps with individual functionality testing. Current scenario requires all tests to be run.

**Comment by NickCraver** [comment]
This is, in part, to support DNX which we working on in beta state. The unit testing story there keeps shifting and the current model is much more workable. Given that all tests run in under a minute in a VM on a laptop from 2 years ago here - I don't think that running all of them is a particular issue. It also makes testing far more portable and dependency-free in general.

If you want to add additional switches to the testing programs to make some optional (a glob or something is probably appropriate) - I'd welcome such a pull request. Since they run so fast though, it admittedly isn't any sort of priority for Marc or I.
