### ISSUE TITLE
release note and/or roadmap?

### ISSUE THREAD

**Issue by Spirch** [StackExchange/dapper-dot-net#348]
On the nugget package page, release note stop at 1.40 but current release is 1.42

What changed between 1.40 and 1.42?

is it possible to get a kind of roadmap, 1.42 was released 5 months ago, when 1.43 will be released?

**Comment by rafakwolf** [comment]
+1
1.50 version too

**Comment by mgravell** [comment]
Excellent question. Oddly enough, one of the biggest reasons this stopped is because this is when I started transitioning to the core-clr build kit, and *at the time* (beta 4, or something) project.json didn't even support release notes (for pushing into the nuget package). Now (beta 8) it does, but it is fairly limited.

My proposal, then, is to create a release notes document separately, and link to that through the release notes section of the nuget (/project.json).

**Comment by mgravell** [comment]
http://stackexchange.github.io/dapper-dot-net/ - subject to change of how this is provided
