### ISSUE TITLE
Know entity type from optional select statements

### ISSUE THREAD

**Issue by mrinalkamboj** [StackExchange/dapper-dot-net#450]
Currently if I have a procedure, which either has multiple Select statements, whose order may change or there's a procedure which may provide an entity, based on some logic, though we are aware of what all are the possible result entity types, I am not able to handle this scenario using current Dapper APIs in a straight forward manner, I have an arduous work around

Simple Repo:

SP1, which takes parameter1, based on the  parameter value result may be entity A or B, in real case either it is  Valid entity or a logical error entity, now even when I know the types that can come out as result, I am not able to use any of the APIs Query<T>, QueryMultiple<T>, since I have no way to figure out the schema fetched, so have to use a round about way, where:
1. Query fetch a dynamic type, 
   
   `var dynamicResult = _connection.Query<dynamic>(query).ToList();`
2. Now assuming the result contains at least 1 row, then I type cast the same to 
   IDictionary<string, object>, using a code like:

`var firstRow = (IDictionary<string, object>)dynamicResult[0];`

Now I compare all the keys in the Dictionary with the available Type properties, and which ever has the complete match is used to fill values, this would too fail if the result set is empty, since I cannot do `dynamicResult[0]`

Is it possible to expose a boolean API like `IsCurrentSchema<T>()`, which helps me identify the fetched type and I can query the same, that would save lot of time and energy in doing round about logic, also is anyone aware of a simpler way to achieve the same, using current APIs

**Comment by mgravell** [comment]
I'm not clear what the IsCurrentSchema method mentioned would do! But idea:
use the data-reader API and GetRowParser API, which would allow you to do
whatever inspection you need, without having tondo any of the
query-building or materialization steps yourself. Would that work?

Currently if I have a procedure, which either has multiple Select
statements, whose order may change or there's a procedure which may provide
an entity, based on some logic, though we are aware of what all are the
possible result entity types, I am not able to handle this scenario using
current Dapper APIs in a straight forward manner, I have an arduous work
around

Simple Repo:

SP1, which takes parameter1, based on the parameter value result may be
entity A or B, in real case either it is Valid entity or a logical error
entity, now even when I know the types that can come out as result, I am
not able to use any of the APIs Query, QueryMultiple, since I have no way
to figure out the schema fetched, so have to use a round about way, where:

1 Query fetch a dynamic type,
var dynamicResult = _connectionQuery(query)ToList();

2 Now assuming the result contains at least 1 row, then I type cast the
same to
IDictionary, using a code like:

var firstRow = (IDictionary)dynamicResult[0];

Now I compare all the keys in the Dictionary with the available Type
properties, and which ever has the complete match is used to fill values,
this would too fail if the result set is empty, since I cannot do
dynamicResult[0]

Is it possible to expose a boolean API like IsCurrentSchema(), which helps
me identify the fetched type and I can query the same, that would save lot
of time and energy in doing round about logic, also is anyone aware of a
simpler way to achieve the same, using current APIs

—
Reply to this email directly or view it on GitHub
<https://github.com/StackExchange/dapper-dot-net/issues/450>.

**Comment by mrinalkamboj** [comment]
@mgravell `bool IsCurrentSchema<T>()` would help in identifying before reading the current result set whether the schema is matching, if yes, then I will proceed with `Read<T>` for Grid Reader or execute standard `Query<T>`, so its an assurance that I can read a Type, a that's what the result offers. In certain cases where we have a logical exception Database sends an error entity instead of standard select result and I have no way to verify. Any other Dapper oriented solution instead of pure ADO.Net

**Comment by mgravell** [comment]
The problem there is: dapper will *accept* most types of most schemas -
there isn't any magic way of saying "yes, that's close enough". There could
be zero bindable columns/members, and *right now* dapper would still give
you back the objects.

**Comment by mrinalkamboj** [comment]
I understand that is by design, so that most of the requests gets filled by some data, but can't there be a mechanism to match all columns between Type T and Select query, only 100% match yields true, anything less or more means false (schema mismatch).
My current workaround, using dynamic type, then typecasting DapperRow to IDictionary<string,object> needs at least 1 row to proceed, so not really a good solution. Any other pointer to a workaround, GetRowParser, I need to check, is it something related to GetSchema from a Reader and proceed by comparing columns with Type properties

**Comment by mgravell** [comment]
GetRowParser works on data-readers, and can be combined with the existing
ExeciteDataReader method. This allows you to add any logic you need between
the "run a query" and "process the results" step, including free access to
check the schema or discriminators, and choose the target type accordingly.
There is an example in the test project.

**Comment by NickCraver** [comment]
@mrinalkamboj were you able to get this working off the test project example?

Here's the relevant test example: https://github.com/StackExchange/dapper-dot-net/blob/a890c30ed0fc074e59092046a49cb393e64ccd2c/Dapper.Tests/Tests.IDataReader.cs#L44

**Comment by NickCraver** [comment]
Closing out to cleanup
