### ISSUE TITLE
Possible SqlMapper QueryAsync wait / timeout handling issue

### ISSUE THREAD

**Issue by osudude** [StackExchange/dapper-dot-net#460]
We are using QueryAsync to execute SQL stored procs.  We then wait on the execution up to a user configurable period of time and later issue various warns / notifications if the wait doesn't return after our specified threshold.
However, while waiting on QueryAsync, we noticed that when 30 second interval elapses, a SqlException  / timeout error wrapped in an aggregate exception is thrown.  We thought that since we did our own wait on QueryAsync that it would override any typical sql command 30 second timeout throwing.  Is this not the case?  Do we need to somehow set Dapper timeout threshold above our own WAIT threshold?

Dapper 1.42
.NET 4.5

thanks

```
var task = cnn.QueryAsync<dynamic>(cmdDef);
var startTime = DateTime.UtcNow;
if (task.Wait(MyWarnThreshold))  //AgggregateException / SqlException (timeout) thrown here on long running stored procs
{
    return task.Result;
}

//Warn, notify, sql monitoring code
.
.
```

**Comment by NickCraver** [comment]
A `.Wait()` only waits on that task to complete for the duration you pass. In this case that task is completing, just not with the result you want. It's completing because it's timing out at a lower level.

For the behavior you want, use the optional `commandTimeout` property  on `QueryAsync` (the unit is milliseconds), like this:

```C#
var task = cnn.QueryAsync<dynamic>(cmdDef, commandTimeout: MyWarnThreshold);
```
