### ISSUE TITLE
type.IsInterface() compile error

### ISSUE THREAD

**Issue by thanhkhanhcntt** [StackExchange/dapper-dot-net#489]
When I compile the code, I got some error at type.IsInterface(),
I edited to type.IsInterface it work, but I wonder why no one report this issue

**Comment by mgravell** [comment]
I think the problem here is some compiler changes that are in Roslyn and
latest, but not in "originally as shipped" Roslyn - especially re overload
resolution and extension methods vs properties. Essentially, I suspect that
if you install the asp.net vNext tools (including the IDE tools and current
Roslyn) : it will start compiling! I suspect this link will do it:
https://go.microsoft.com/fwlink/?LinkId=627627

Yes, that's vexing. I'm actually slightly limited because I don't have a
vanilla VS2015 to try it on. What I probably need to do is to set up a VM
(or borrow an Azure VM) with vanilla VS2015 to try this on.

On 29 March 2016 at 05:28, thanhkhanhcntt <notifications@github.com> wrote:

> When I compile the code, I got some error at type.IsInterface(),
> I edited to type.IsInterface it work, but I wonder why no one report this
> issue
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/489>
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
Fixed in current code - likely an early core issue.
