### ISSUE TITLE
Add dynamic parameter for Oracle.

### ISSUE THREAD

**Issue by ArseniySavin** [StackExchange/dapper-dot-net#580]
Hi there. 
Can you add something like this [OracleDynamicParameters](https://gist.github.com/vijaysg/3096151)?
It would be great if it will be available from the basic package.

**Comment by NickCraver** [comment]
Unfortunately we can't do this in the base package, because that would require the base package to take a dependency on Oracle. Dapper depends on the shared interfaces, not additional libraries not in the framework already.

There's nothing stopping someone from making a `Dapper.Oracle` with helpers such as this, though...

**Comment by ArseniySavin** [comment]
Ok. Thank you. Maybe. I will try do it in my fork.
