### ISSUE TITLE
QueryMultiple with a SQLCeConnection doesn't work

### ISSUE THREAD

**Issue by Rojiferio** [StackExchange/dapper-dot-net#630]
I'm trying to execute a QueryMultiple over a SQL Compact 4.0 database, and retuned an error:
System.Data.SqlServerCe.SqlCeException: Error al analizar la consulta. [ Token line number = 12,Token line offset = 37,Token in error = SELECT]

So, is possible to execute multiple queries in SQL Compact?

Thanks

**Comment by NickCraver** [comment]
What was the code? The error message indicates unable to parse...but I have no idea what we're talking about here without some code. Can you add yours?

**Comment by NickCraver** [comment]
I ran into this porting MiniProfiler as well. In short: this is a SQL Server CE limitation (one query per catch) that we cannot do anything at all about. It's just something the database doesn't support.

Closing this out to cleanup since there is, unfortunately, nothing we can do. I wish there was, I'd use it in MiniProfiler :)
