### ISSUE TITLE
DynamicParameters do not support "like" query 

### ISSUE THREAD

**Issue by qq1211178784** [StackExchange/dapper-dot-net#639]
I have a db table "T_Course",and a query sql bellow, it doesn't work unless the name parameter added "%"
```C#
public IEnumerable<T_Course> GetList(string name) 
{
    DynamicParameters p = new DynamicParameters();
    StringBuilder condition=new StringBuilder();
    condition.Append("where 1=1 ");
    if (!string.IsNullOrWhiteSpace(name))
    {
        condition.Append("and Name like @Name");
        p.Add("@Name", name, System.Data.DbType.String);
    }
    using (var conn = ConnectionFactory.GetOpenConnection())
    {
        return conn.Query<T_Course>("select * from T_Course " +condition.ToString(), p);
    }
}
```

**Comment by NickCraver** [comment]
That's the correct behavior, you need to manually put in `%` for where you want to search. SQL does not assume "contains" (e.g. `%term%`), you need to tell it what you're looking for. That could be `%term` (ends with), `term%` (starts with), `%term%` (contains) or even something like `t%m`.

SQL simply makes no assumptions about this, on any platform as far as I'm aware. You need to specify. If you're doing contains always, you can do: 
```C#
p.Add("@Name", "%" + name + "%", System.Data.DbType.String);
```

You could also greatly simplify overall, since unused parameters aren't an issue:
```C#
public IEnumerable<T_Course> GetList(string name) 
{
    var sql = string.IsNullOrWhiteSpace(name) 
      ? "SELECT * FROM T_Course"
      : "SELECT * FROM T_Course AND Name LIKE @Name";
    using (var conn = ConnectionFactory.GetOpenConnection())
    {
        return conn.Query<T_Course>(sql, new { Name = "%" + name + "%" });
    }
}
```

**Comment by NickCraver** [comment]
Closing this out to cleanup, please let me know if that doesn't solve your issue.

**Comment by qq1211178784** [comment]
Thanks for your detailed explanation! sorry that I didn't noticed this email recently!
