### ISSUE TITLE
The ConnectionString property has not been initialized.

### ISSUE THREAD

**Issue by lasikye** [StackExchange/dapper-dot-net#664]
Below is my method, when it is running, I debug found the result had values before connection released, but after connection release, result will thow an exception as "The ConnectionString property has not been initialized."

`public IEnumerable<T> Query<T>(string sql, object param = null, IDbTransaction transaction = null, bool buffered = true, int? commandTimeout = null, CommandType? commandType = CommandType.Text)
        {
            IEnumerable<T> result;
            using (IDbConnection con = ConnectionFactory.Instance.GetConnection())
            {
                con.Open();
                result = con.Query<T>(sql, param, transaction, buffered, commandTimeout, commandType);
                con.Close();
            }
            return result;
        }`

**Comment by lasikye** [comment]
![capture](https://cloud.githubusercontent.com/assets/8716784/21385109/3cd88f1c-c7a8-11e6-8ada-6f184398f359.JPG)

**Comment by NickCraver** [comment]
I see that you have `buffered` set to `false`. If you do this and immediately close and dispose the connection, you're doing so before the results are read. You have 2 choices here:
- Let Dapper buffer these internally for you (the default, `buffered: true`)
- Or consume the results yourself before closing and disposing of the connection.

The current code has the effect of shutting the door while the results are still walking in, so that'll almost always blow up. The only way it'll succeed is if the query was so far and the result set so small as to finish before the `.Close()` call gets hit.

**Comment by lasikye** [comment]
Ok. Got it. Thanks Nick.



On Wed, Dec 21, 2016 at 8:31 PM +0800, "Nick Craver" <notifications@github.com<mailto:notifications@github.com>> wrote:


I see that you have buffered set to false. If you do this and immediately close and dispose the connection, you're doing so before the results are read. You have 2 choices here:

  *   Let Dapper buffer these internally for you (the default, buffered: true)
  *   Or consume the results yourself before closing and disposing of the connection.

The current code has the effect of shutting the door while the results are still walking in, so that'll almost always blow up. The only way it'll succeed is if the query was so far and the result set so small as to finish before the .Close() call gets hit.

**Comment by NickCraver** [comment]
@lasikye anything else I can help with here, or want me to close this one out?
