### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by ApiO** [StackExchange/dapper-dot-net#665]
Hi,

First, I have to thank you for Dapper !

Sometimes, I really need to have some properties set and I don’t like to have to trust the guy who wrote the sql part. Has he done his job properly? Does he send me the correct data type? I hope to have no default value here!
These are questions that I ask systematically to myself and I find it uncomfortable. The stability of this application layer depends on the goodwill of the devs, which becomes a technical debt and a lot of dead codes.
I wish I could express validation rules on a model to assert that my data are correctly binded, but not all the time just in dev/integration. 

Does a plugin / extension already do that?

I could write and share that if needed.

**Comment by NickCraver** [comment]
There are some libraries built on top of Dapper that do some or all of what you want...but I'm not sure of the names honestly. This isn't something the core of Dapper aims to do, hence the "Micro-ORM" label. Full model validation, etc. may mean you're more seeking the likes of Entity Framework and the like.

Dapper gives me control and more performance, but at the expense of less abstraction. Sometimes (many times) that just isn't the right fit. But hey, that's why we have such variety in the ORM space :) Good luck!

**Comment by NickCraver** [comment]
Closing out to cleanup, let me know if there are lingering questions :)

**Comment by ApiO** [comment]
It's ok and thank you for your previous response.

Just for the archive, I haven't found what I search. There is a lots of extensions for CRUD or fork with features far away from the micro-ORM phiolosophy, but not binding validation.

To me Dapper is near to be perfect. It must be possible to add a sexy and nonintrusive validation. I will spend some time to design a solution and hope to be able to share it.
