### ISSUE TITLE
Implement DiagnosticSource

### ISSUE THREAD

**Issue by Jetski5822** [StackExchange/dapper-dot-net#668]
Could we get DiagnosticSource implemented inside of Dapper please?

It would allow a easier for external code to hook in to the core to see what sql is produced. (I want to hook it in to Glimpse for Orchard Core).

Unless you have a better suggestion?

**Comment by NickCraver** [comment]
This dependency isn't necessary since all of the ADO.NET bits (IDbConnection), etc. are already standard. You simply control the connection passed into Dapper and record what you want. 

For example we do this in MiniProfiler (so *very* close to your use case), calling it a `ProfiledDbConnection` (and related: `ProfiledDbCommand`). There you can observe any of the commands going through. If you're worried about scale: we use this for every SQL command at Stack Overflow with no issue.

Here's how MiniProfiler does it: https://github.com/MiniProfiler/dotnet/blob/master/StackExchange.Profiling/Data/ProfiledDbConnection.cs

**Comment by Jetski5822** [comment]
Groovy!!! - Ill give it ago, cheers.
